### ISSUE TITLE
Issue in README

### ISSUE THREAD

**Issue by dev1911** [NikhilMJagtap/AndroidND-Compilation#1]
The screenshot is not appearing on the README.md file of the sandwich-club app.  
@NikhilMJagtap kindly see into this

**Comment by NikhilMJagtap** [comment]
Thank you for bringing that to my notice. Screenshots visible after [this](https://github.com/NikhilMJagtap/AndroidND-Compilation/commit/171a84134ee8cf950c68678608f1f46c53570223) commit. I hope this issue can be closed now. Peace!
